### PR TITLE
Convert to ES6 that is supported on Node 4, commonjs modules and remove Babel

### PR DESCRIPTION
**Pull request by corbinu**
This removes Babel, converts to commonjs modules and removes other ES6 features not supported on Node 4. I think it was all destructuring.

Updated version of #8 which removes .defaults and rebased on master

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
I think you might have accidentally gotten rid of some of the previous commits to master on this branch.

**Comment by corbinu** [comment]
Ya idk what happened seemed right will fix

**Comment by corbinu** [comment]
@not-an-aardvark Looks like travis just needed to be updated to match :)

**Comment by not-an-aardvark** [comment]
No, I mean that this PR makes a bunch of changes to unrelated files such as README.md, effectively reverting commits like cf38df0a6003cdcb6f9c3f1622821b354016c8d6.

**Comment by soda0289** [comment]
I think you need to rebase off of master.

**Comment by not-an-aardvark** [comment]
Is it possible that when you removed the commits that were on your master, you were accidentally comparing to the estools/escope repo instead of eslint/eslint-scope?

**Comment by corbinu** [comment]
@not-an-aardvark Ahh I know what I did wrong sorry

**Pull request closed without merging**
