### PR TITLE
Add check for node.body in referencer

### PR DESCRIPTION
**Pull request by corbinu**
So happy to make this PR!! Obviously this fixes issues for scoping typescript methods without a body per https://github.com/eslint/typescript-eslint-parser/issues/92

### CODE REVIEW

**Comment by corbinu** [comment]
@JamesHenry hah yes sorry I am a lurker have been wanting to help more, but you know work :/ figured this one took me all of 5 min :) 

Should be all set!

**Comment by corbinu** [comment]
@nzakas Sure may take me some digging but once the rest of my work is done today will try to take a crack at it.

**Comment by corbinu** [comment]
@JamesHenry I am going to be super busy till the weekend. If you want to do this instead before then is totally fine with me :)

**Comment by JamesHenry** [comment]
@corbinu any update on this?

**Comment by corbinu** [comment]
@JamesHenry sorry work has gotten away from me. I should have some time thrusday but if somebody else wants to pickup the tests is fine :)

**Comment by soda0289** [comment]
I don't mind writing tests. Would love to help. I'll take a shot at it later today.

**Comment by corbinu** [comment]
@soda0289 Sure thanks that would really help!

**Comment by soda0289** [comment]
I added some tests for typescript. Pull request can be found here:
https://github.com/corbinu/eslint-scope/pull/1

I dont think the scope is correct. For example the abstract class is not found in the scope. I think the other test, for multiple function declartion, are correct just need to double check.

I also had to add a check to scope.js to return false when body is not found in the function isStrictScope().

**Comment by corbinu** [comment]
Thanks will add them to mine.

**Comment by corbinu** [comment]
@JamesHenry @nzakas @soda0289 Was nice enough to get some tests working this should be good to go. @soda0289 Is going to do another PR that adds changes and tests to eslint-scope to properly scope Typescript Abstract classes.

**Comment by JamesHenry** [comment]
Thanks so much for your efforts on this guys!

I was never a contributor to escope, and I do not feel I am in a good position to be able to pass judgement on how well these test cases match expectations. The code itself certainly seems fine 👍 

@nzakas Requested them originally, and certainly has been an important contributor to escope in the past, so his review here is key.

@corbinu The main thing from me is to make sure that this branch is up to date, there are currently conflicts

**Comment by corbinu** [comment]
@JamesHenry should be all set!

**Comment by corbinu** [comment]
@JamesHenry Sorry if I jacked the rebase is that better?

**Comment by nzakas** [comment]
Hmm, it's not letting me merge for some reason. Will try again later. 

@corbinu thanks for your help. In the future, please be sure to follow our commit message guidelines. It helps the process be a bit smoother.

**Comment by ilyavolodin** [comment]
@nzakas Merge was disabled because @JamesHenry have requested changes and review was not approved. I'll merge this in as "Update"

**Comment by JamesHenry** [comment]
👍

**Comment by nzakas** [comment]
Ah weird, that request for changes didn't show up in the mobile view. Thanks!

**Pull request merged**
