### PR TITLE
Fix arrow function scope strictness

### LINKED ISSUE #49: ArrowFunctionExpression's scope is always strict scope
It seems to be deliberate that `eslint-scope` always sets `isStrict` to `true` for arrow function scopes. But this is not how it works in all the engines I could get my hands to.

I used assignment to an undeclared variable to check if the code is in strict mode:

With explicit strict mode, we get an error:
```bash
node -e '"use strict"; (() => { a = 5 })()'
# ReferenceError: a is not defined
```

Without `"use strict"` an error is not thrown, which means it's not in strict mode, but `eslint-scope` would treat the scope as strict anyway:
```bash
node -e '(() => { x = 1 })()'
```

I also checked with the spec's definition of strict mode code, and it seems that arrow functions should not get any special treatment (only classes should): https://www.ecma-international.org/ecma-262/#sec-strict-mode-code

https://github.com/eslint/eslint-scope/blob/3e69fdcf102082f3b3c419d0864d7ed90323f4ca/lib/scope.js#L52-L55

https://github.com/eslint/eslint-scope/blob/3e69fdcf102082f3b3c419d0864d7ed90323f4ca/tests/es6-arrow-function-expression.js#L55

### PR DESCRIPTION
**Pull request by futpib**
Fixes #49

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Will this have an effect on arrow functions with duplicate arguments?

```js
(duplicateName, duplicateName) => {}
```

Duplicate argument names are disallowed in strict mode functions, and also in arrow functions. (Aside from duplicate arguments, I think there might be other features like this, but I'm not sure.) If the previous code was relying on arrow functions always being considered strict mode in order to implement those checks, then it might be necessary to do the checks explicitly now in order to preserve correct behavior.

(I'm not very familiar with the `eslint-scope` codebase, so I'm not sure whether this is actually the case. I'm just bringing it up since it seems like a plausible thing that someone could have missed.)

**Comment by mysticatea** [comment]
I don't think `eslint-scope` checks duplication. If a variable was redeclared, the `Variable` object has two `Definition`s in `defs` property.

**Comment by not-an-aardvark** [comment]
Ok, sounds good.

**Comment by not-an-aardvark** [comment]
FYI, this change has been temporarily reverted because it was causing some crashes in ESLint. See https://github.com/eslint/eslint-scope/pull/51 for more information.

**Pull request merged**
