### PR TITLE
Chore: Remove estraverse and move syntax options in

### PR DESCRIPTION
**Pull request by corbinu**
Fix lintingAs #17 pointed out estraverse is only a dependency for list of possible syntax strings which is probably not necessary so I just pulled them in.

### CODE REVIEW

**Comment by ilyavolodin** [comment]
I think at some point, the idea was to not have hard-coded list of nodes, but instead have parser pass it in. This way, if parser produces some non-standard nodes, they still can be accounted for.

**Comment by corbinu** [comment]
@ilyavolodin I totally get that thought also some of the driver here is the lack of activity on estraverse especially since it was such a small list and if we are going to be adding some new nodes then we were going to have to maintain some hard coded list anyway so the maintenance burden on this repo was equal

**Comment by ilyavolodin** [comment]
Fair enough. I'm not really familiar with the issue, and don't know how this ties into `escope.VisitorsKeys` property. So I'll let somebody else review and merge.

**Comment by nzakas** [comment]
I don't think we can make this change (yet?). Currently, modifying estraverse VisitorKeys from inside ESLint gives us the ability to change how all the traversals work (esrecurse, escope, estraverse). Moving the VisitorKeys into a static location means we will no longer be able to do that. 

I think for now we should not consider such a change. After we've done a first ESLint release with eslint-scope then we will be in a better position to evaluate something like this.

**Comment by corbinu** [comment]
@nzakas  I don't understand eslint-scope doesn't use VisitorKeys only esrecurse does. This only hard codes the syntax tree. I am going to close this though as I think the better path is to prepose to the TSC that estraverse and esrecurse both be folded into eslint-scope in their entireity as they are tiny projects and it seems like a much cleaner solution. Also it would let us enable those kind of changes inside of eslint better rather than making them worse.

**Pull request closed without merging**
