### PR TITLE
Chore: Convert to ES6 that is supported on Node 4, commonjs modules and remove Babel

### PR DESCRIPTION
**Pull request by corbinu**
I appear to have messed up the rebase. Think the issue was I never should have merged first. 

This removes Babel, converts to commonjs modules and removes other ES6 features not supported on Node 4. I think it was all destructuring.

Updated version of #8 which removes .defaults and rebased on master

### CODE REVIEW

**Comment by platinumazure** [comment]
As you've no doubt figured out by now, it's generally better to rebase your topic on master rather than merge master into the topic branch. (Definitely do a fast-forward merge when you're pulling the main repo's master branch into your local master, though.) I'm sorry you've had a frustrating experience and I hope things go better in the future :smile:

**Comment by corbinu** [comment]
@platinumazure Ya the bigger issue appears to have been undoing that mistake. Thanks really wasn't to frustrating just hoping that I am not annoying everybody by closing and reopening as honestly I just find that easiest. :)

**Comment by nzakas** [comment]
Note: this commit message should be prefixed with "Chore:" when merged to follow our commit message guidelines.

**Comment by corbinu** [comment]
@nzakas Sorry fixed!

**Comment by corbinu** [comment]
@JamesHenry Should be all set!

**Comment by corbinu** [comment]
@JamesHenry The travis work is still there this one is just the one that needs to come in first

**Comment by JamesHenry** [comment]
Brilliant! Thanks @corbinu you've got it nailed now 😄

**Comment by corbinu** [comment]
Thanks for the help

**Pull request merged**
