### PR TITLE
Updated `esrecurse` to ^4.3.0

### PR DESCRIPTION
**Pull request by sanex3339**
Updated esrecurse version to support latest estraverse with optional chaining support

https://github.com/estools/esrecurse/pull/22

### CODE REVIEW

**Comment by sanex3339** [comment]
Please release a new version with this

**Comment by nzakas** [comment]
@sanex3339 please have some patience. We are all doing what we can.

**Comment by sanex3339** [comment]
When this will be released?

**Comment by kaicataldo** [comment]
We do releases every two weeks. This was just released.

**Comment by sanex3339** [comment]
Thank you

**Pull request merged**
