### PR TITLE
Chore: Remove es6-map and es6-weakmap as they are included in node4

### PR DESCRIPTION
**Pull request by corbinu**
Remove es6-map and es6-weakmap as they are included in node4

### CODE REVIEW

**Comment by JamesHenry** [comment]
This LGTM, will do a proper review as soon as we get the node versions for the travis build sorted

**Comment by corbinu** [comment]
@JamesHenry Thanks ya #11 just needs to land first

**Comment by JamesHenry** [comment]
Do you need help with rebasing? You are still doing merge commits into the other branches and so we are ending up with very messy commit histories on these PRs

**Comment by corbinu** [comment]
@JamesHenry Yes please sorry I was doing "git rebase --interactive" and squashing down to one commit but then every time for some reason the merge ends up at the end not sure why

**Comment by JamesHenry** [comment]
I am definitely not a git expert, but `git rebase --interactive` has always worked out well for me.

What I tend to do is:

1) Make sure you have the eslint repo as a secondary remote before starting - in your case you are working on a fork, so your `origin` is based on that. I usually call my second origin which points at the original remote repo `upstream`, so in your case I would have `origin` which is `corbinu/eslint-scope` and `upstream` which is `eslint/eslint-scope`

2) Fetch the absolute latest from `eslint/eslint-scope` by doing `git fetch upstream` (given your secondary remote is set up as outline in (1))

3) Do an interactive rebase for your current branch against that latest by doing `git rebase -i upstream/master`

4) Squash/drop/rename commits as appropriate so that you end up with a single commit which summarises all of your work which should go in the PR

As I say, I am definitely not an expert, but that method works well for me when I am working on forks.

Hope that helps!

**Comment by corbinu** [comment]
@JamesHenry Strange I am pretty sure thats what I am doing .. I have my orginal brach (yes I know I misspelled it) that points to eslint-scope.git#master

I switch to that orginal branch. Do "git pull" then I switch to the branch I am working on and "git rebase --interactive orginal" and squash it down.

**Comment by JamesHenry** [comment]
What is the output when you run `git remote -v`?

**Comment by corbinu** [comment]
origin	git@github.com:corbinu/eslint-scope.git (fetch)
origin	git@github.com:corbinu/eslint-scope.git (push)
original	git@github.com:eslint/eslint-scope.git (fetch)
original	git@github.com:eslint/eslint-scope.git (push)

**Comment by corbinu** [comment]
Ok I tried it again but then I end up with this
```
To github.com:corbinu/eslint-scope.git
 ! [rejected]        node-4 -> node-4 (non-fast-forward)
error: failed to push some refs to 'git@github.com:corbinu/eslint-scope.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details
```
and I when I do get pull thats when that merge gets created

**Comment by soda0289** [comment]
git push --force

**Comment by JamesHenry** [comment]
Is that when you are pushing after your rebase?

If so that is perfectly normal, you have to force push after the rebase. You need to do `git push -f`

**Comment by corbinu** [comment]
Ahhh ok great thanks!

**Comment by soda0289** [comment]
You should probally prefix the commit message with Chore.
You can do a git commit --amend then do another git push --force

**Comment by JamesHenry** [comment]
Ah, @corbinu you see now that you have rebased that other work containing the travis yaml file has disappeared! This is why the rebasing is so important. Let's reopen that other PR and get that merged in first

**Comment by corbinu** [comment]
@soda0289 Thanks did on the babel removal will change this one when I rebase on that

**Comment by JamesHenry** [comment]
@corbinu The other PR has been merged, this is now ready to be rebased (again 😄 )

**Comment by corbinu** [comment]
@JamesHenry Good to go thanks!

**Pull request merged**
